name: mega
description: Mega widgets and themes for Flutter.
homepage: https://github.com/MahanRahmati/flutter_mega

version: 0.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
